version: '3'

services:
  api:
    image: docker.pkg.github.com/bierpedia/api/api:latest
    environment:
      - CUSTOMCONNSTR_Postgres=Host=db;Database=bierpedia;Username=bierpedia;Password=bierpedia;
      - VIRTUAL_HOST=api.bierpedia.org
      - LETSENCRYPT_HOST=api.bierpedia.org
    expose:
      - "80"
    networks:
      - default
      - outside
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=bierpedia
      - POSTGRES_PASSWORD=bierpedia
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    networks:
      - default

volumes:
  pgdata:

networks:
  outside:
    external:
      name: nginx_network

